### PR TITLE
Port to 1.18

### PR DESCRIPTION
**Pull request by PaintNinja**
Haven't changed the readme or mods.toml to credit me for the port as it was pretty trivial. If you want to credit feel free though.

### CODE REVIEW

**Comment by eerussianguy** [comment]
This looks fine, but I'm not entirely sure about where the apache license bit comes in? This mod is MIT licensed

**Comment by PaintNinja** [comment]
I'm not sure where you're getting an apache license from... Could you point it out to me please?

I just based it off the 1.17 branch and didn't touch any files relating to licensing as far as I'm aware.

**Comment by eerussianguy** [comment]
Oh I was mistaken -- something to do with the gradle files I read incorrectly

**Comment by eerussianguy** [comment]
https://github.com/eerussianguy/Better-Foliage/commit/fde244a9298c671d696155575aca24b441ae852b

**Comment by eerussianguy** [comment]
Thanks for the work you've been putting in around the modding community -- it is people like you that keep the community going. For real

**Pull request closed without merging**
